# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

cluster = {
  "master" => { :ip => "10.10.10.100", :cpus => 2, :mem => 2048 },  "worker1" => { :ip => "10.10.10.101", :cpus => 2, :mem => 2048 },   "worker2" => { :ip => "10.10.10.102", :cpus => 2, :mem => 2048 }, "worker3" => { :ip => "10.10.10.103", :cpus => 2, :mem => 2048 }


}
 

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provision "shell", path: "run.sh"

  cluster.each_with_index do |(hostname, info), index|

    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "ubuntu/xenial64"

        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]

      end # end provider

    end # end config

  end # end cluster
end
